# Generated by Django 5.2.11 on 2026-02-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-total_score']},
        ),
        migrations.AddField(
            model_name='participant',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
