# Generated by Django 5.2.11 on 2026-02-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_participant_options_participant_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.CharField(blank=True, help_text='VK video embed URL', max_length=500, null=True),
        ),
    ]
