# Generated by Django 5.2.11 on 2026-02-16 09:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_game_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['-total_score'], 'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['order'], 'verbose_name': 'Раунд', 'verbose_name_plural': 'Раунды'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='bet_used',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(null=True, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='points_awarded',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начисленные очки'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название команды / имя'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=255, verbose_name='ID пользователя (сессия)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='game',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('team', 'команда'), ('individual', 'индивидуально')], default='individual', max_length=20, verbose_name='Режим'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='game',
            name='video_url',
            field=models.CharField(blank=True, help_text='VK video embed URL', max_length=500, null=True, verbose_name='Видео (embed URL)'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время регистрации'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='session_key',
            field=models.CharField(max_length=255, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название команды / имя'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='total_score',
            field=models.IntegerField(default=0, verbose_name='Всего очков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='allow_bet',
            field=models.BooleanField(default=False, verbose_name='Разрешена ставка'),
        ),
        migrations.AlterField(
            model_name='question',
            name='bet_multiplier',
            field=models.PositiveIntegerField(default=1, verbose_name='Множитель ставки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.TextField(blank=True, help_text='For choice must match one option; for open — moderator reference', null=True, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, help_text='Store list of option strings', null=True, verbose_name='Варианты (JSON)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Очки'),
        ),
        migrations.AlterField(
            model_name='question',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.round', verbose_name='Раунд'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('choice', 'выбор'), ('open', 'открытый')], default='choice', max_length=10, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='round',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание раунда'),
        ),
        migrations.AlterField(
            model_name='round',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='quiz.game', verbose_name='Игра'),
        ),
        migrations.AlterField(
            model_name='round',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='round',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название раунда'),
        ),
    ]
