# Generated by Django 5.2.11 on 2026-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_add_active_question_accepting_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active_question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта активного вопроса'),
        ),
    ]
